### ISSUE TITLE
separate analytic results out from json files

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/ACRO#37]

**Comment by jim-smith** [comment]
Put each research output into a separate file.
One overall json file with sections for each output.
- issue will be whether meta data is huge for large tables
  - need way to reference problematic cells by index rather than mask for whole table
- **Q**: should the meta data for an output contain something like line numbers in submitted code?
- facility to capture researchers comments , "exception requests"
-- facility to capture decisions  from more than one output checkers' (with their id) 
   - **Q**: what if there are two output checkers?
   - **Q**: are these from  finite set of responses or free text?
- **Q**: do we need a 'content type' field for each output
- **Q**: do we treat a revised version (after rejection) as a new case or as a revision so that we can learn from the edit history.

**Comment by rpreen** [comment]
**Goal:** `finalise()` writes each desired output to a separate *data* file (e.g., csv for DataFrames) and creates a single *metadata* json file ("results.json") that contains the paths to each of the output files and the results from SDC.

**Requires:**
1. Changing the `finalise()` function to always write json output.
https://github.com/AI-SDC/ACRO/blob/0513b6daa7e67d704aea93f5edf3d0e37daf7e9e/acro/acro.py#L66-L88

2. Changing the `finalise_json()` function so that:
    a.  each `output["output"]` is written to a separate *data* file with the file name being the output key, e.g. a Pandas DataFrame is written to a file named "output_0.csv".
    b. Change each `output["output"]` so that the value of the *metadata* json file contains the path to the previously created data file.
https://github.com/AI-SDC/ACRO/blob/0513b6daa7e67d704aea93f5edf3d0e37daf7e9e/acro/utils.py#L57-L76


**Other thoughts:**

In the current version of ACRO all outputs are DataFrames (including the results from regressions), we will need to support other types so a generic `def add_unchecked_output(filename: str) -> None` can be used to add things like png figures with a decision of "review".

**Q:** is csv appropriate for writing hierarchical tables (DataFrames) or do we need to use something like `pickle`?
**Q:** do we need a 'content type' field for each output or do we just infer it from the data type, e.g., all DataFrames are written to a pickle, and all strings are names of files and the file extension is used to infer type?
